FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy

COPY . /app

ENV PATH="/app/.venv/bin:$PATH"

RUN uv sync --frozen

CMD [ "pytest", "--maxfail=1", "--disable-warnings", "--cov=app", "--cov-report=html:/app/coverage" ]